/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('ant-design-vue/es')['Affix']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AboutView: typeof import('./../src/views/AboutView.vue')['default']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    Account_setting: typeof import('./../src/views/profile/account_setting.vue')['default']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    Ai: typeof import('./../src/views/one-to-more/Ai.vue')['default']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AiTools: typeof import('./../src/views/ai-tools/index.vue')['default']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Bar: typeof import('./../src/views/profile/bar.vue')['default']
    Common_tool_header: typeof import('./../src/views/ai-tools/common_tool_header.vue')['default']
    HomeView: typeof import('./../src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    ImageComp: typeof import('./../src/components/image-comp/index.vue')['default']
    Login: typeof import('./../src/views/login/index.vue')['default']
    My_file: typeof import('./../src/views/profile/my_file.vue')['default']
    Navbar: typeof import('./../src/components/navbar/index.vue')['default']
    OneToMore: typeof import('./../src/views/one-to-more/index.vue')['default']
    OneToOne: typeof import('./../src/views/one-to-one/index.vue')['default']
    OnlineCodeRunner: typeof import('./../src/views/online-code-runner/index.vue')['default']
    Pic_to_video: typeof import('./../src/views/ai-tools/pic_to_video.vue')['default']
    Pic_to_video_profile: typeof import('./../src/views/profile/pic_to_video_profile.vue')['default']
    Profile: typeof import('./../src/views/profile/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Virtual_company: typeof import('./../src/views/ai-tools/virtual_company.vue')['default']
    Virtual_company_profile: typeof import('./../src/views/profile/virtual_company_profile.vue')['default']
  }
}
